# Generated by Django 4.0.3 on 2022-11-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(choices=[('hw', 'Height/Weight'), ('bloodpresure', 'BloodPresure'), ('heartrate', 'Heartrate')], max_length=15)),
                ('componentValue', models.CharField(max_length=15)),
                ('measureDate', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalapp.patient')),
            ],
        ),
    ]
