# Generated by Django 4.0.3 on 2022-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='componentValue',
            field=models.IntegerField(),
        ),
    ]
